// <auto-generated/>
#pragma warning disable 0067, 0108
// ------------------------------------
// 
// Assembly PexDemo
// 
// ------------------------------------
namespace PexDemo.Stubs
{
    /// <summary>Stub of Class1</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Stubs", "0.14.40610.2")]
    [global::System.Serializable]
    [global::System.Diagnostics.DebuggerDisplay("Stub = Class1")]
    [global::System.Diagnostics.DebuggerStepThrough]
    public partial class SClass1
      : global::PexDemo.Class1
      , global::Microsoft.Stubs.Framework.IStub
      , global::Microsoft.Stubs.Framework.IPartialStub
    {
        [global::System.Diagnostics.DebuggerHidden]
        public SClass1()
        {
            this.Initialize();
        }

        /// <summary>Gets or sets a value that indicates if the base method should be called instead of the fallback behavior</summary>
        public bool CallBase
        {
            [global::System.Diagnostics.DebuggerHidden]
            get
            {
                return this.callBase;
            }
            [global::System.Diagnostics.DebuggerHidden]
            set
            {
                this.callBase = value;
            }
        }

        /// <summary>Gets or sets the fallback behavior.</summary>
        public global::Microsoft.Stubs.Framework.IStubBehavior FallbackBehavior
        {
            [global::System.Diagnostics.DebuggerHidden]
            get
            {
                return this.defaultStub;
            }
            [global::System.Diagnostics.DebuggerHidden]
            set
            {
                this.defaultStub = value;
            }
        }

        /// <summary>Initializes a new instance of type SClass1</summary>
        [global::System.Diagnostics.DebuggerHidden]
        private void Initialize()
        {
            this.defaultStub =
              global::Microsoft.Stubs.Framework.StubFallbackBehavior.Current;
        }

        private bool callBase;

        private global::Microsoft.Stubs.Framework.IStubBehavior defaultStub;
    }
}

